name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter yt-dlp pillow requests pyinstaller
    
    - name: Build Windows executable
      run: |
        pyinstaller --onefile project.py
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: YouTubeDownloader-Windows
        path: dist/YouTubeDownloader.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter yt-dlp pillow requests pyinstaller
    
    - name: Build Linux executable
      run: |
        pyinstaller --onefile project.py
        chmod +x dist/YouTubeDownloader
    
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: YouTubeDownloader-Linux
        path: dist/YouTubeDownloader

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        brew install ffmpeg
        python -m pip install --upgrade pip
        pip install customtkinter yt-dlp pillow requests pyinstaller
    
    - name: Build macOS executable
      run: |
        pyinstaller --onefile project.py
        chmod +x dist/YouTubeDownloader
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: YouTubeDownloader-macOS
        path: dist/YouTubeDownloader
